# Generated by Django 3.2.14 on 2023-07-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=88)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TollBooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=88)),
                ('created', models.DateTimeField(auto_now=True)),
                ('toll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.toll')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TollPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.CharField(choices=[('S', 'Single Pass'), ('R', 'Return Pass'), ('7D', '7 Day pass')], max_length=2)),
                ('valid_from', models.DateTimeField()),
                ('valid_untill', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registraion_num', models.CharField(max_length=88, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TollTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amt_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toll_booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.tollbooth')),
                ('toll_pass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.tollpass')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='tollpass',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.vehicle'),
        ),
    ]
